# Generated by Django 5.0.3 on 2024-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_Img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
